<!DOCTYPE html>
<html>
	<head>	
		<!-- BootStrap 5 Call -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

		<!-- Tab Title -->
		<title> Top Animals - My Dog! </title>									
	</head>
	<body>
		<!-- BootStrap 5 Call -->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>			
			
		<div class="container-fluid text-center fs-1 bg-secondary text-dark">
  			<!-- Page Title -->
  			<p class>My Top Favorite Animals</p>
  
  			<!-- Buttons Container with Black Background -->
  			<div class="container-fluid">
    				<div class="d-flex justify-content-center py-3" style="margin-top: -40px;">
      					<a href="index.html">
        					<button type="button" class="btn btn-dark mx-2">Homepage</button>
      					</a>
      					<a href="details.html">
       	 					<button type="button" class="btn btn-dark mx-2">My Dog</button>
      					</a>
      					<a href="about.html">
        					<button type="button" class="btn btn-dark mx-2">Taking Care of a Puppy</button>
      					</a>
    				</div>
  			</div>
		</div>

		<br>
		<div class="container">
			<div class="row align-items-center">
			  
				<div class="col-md-6">
					<img src="blue.JPEG" alt="blue" class="img-fluid">
				</div>
			  	
				<div class="col-md-6">
					<h2>Blue</h2>
					<p>This is my dog. His name is Blue. He is 4 months old and weighs 38 lbs. He is a full Golden Retriever, and he loves to play. 
						He is friendly with all other dogs and loves people. He is a little on edge with cats, but that is mostly because cats 
						usually do not like to horseplay with him.</p>

					<p> We got him from a family in Lexington, NC, who could no longer keep him. I was looking for a dog at the time and was more 
						than willing to take him in. He had a lot of health problems when I got him, but after multiple trips to the vet, he is 
						now healthy and happy. I have always loved Golden Retrievers because my family got one before I moved out, and it was the 
						most loyal and sweet dog ever. Her name is Winnie. He gets plenty of attention and often goes to see Winnie.
					</p>
			  	</div>
			</div>
		  </div>
	</body>
</html>